006 - Loyalties, Rewards
voucherifyio/voucherify-openapi pull request #491
Opened 2023-10-13 14:00 UTC by weronika-kurczyna

2023-10-18 10:09 UTC, p-zielinski requested changes
add type material and validation_rules
pls

2023-10-19 14:13 UTC, weronika-kurczyna commented
I did not removed the `4_obj_reward_object` because it's still used in 20 places and this must be verified when updating other endpoints (and that's why it wasn't updated to `reward` in `md.tables.ts`

2023-10-19 14:14 UTC, weronika-kurczyna commented
4_obj_reward_assignment_object - same situation, still used in 7 places in the code

2023-10-20 09:08 UTC, p-zielinski approved these changes

2023-10-20 09:10 UTC, merged