Pz/stackable validation
voucherifyio/voucherify-openapi pull request #525
Opened 2023-10-30 15:43 UTC by p-zielinski

## 20231102 - Stackable Validations and stackable redemptions

**Removed schemas**
- Customer
- Referrer

**Added schemas**

- ReferrerRequest
- ReferrerResponse
- CustomerRequest
- CustomerResponse
- Discount
- VoucherAssets
- ValidationsValidateResponseBody
- ValidationsRedeemableApplicable
- ValidationsRedeemableInapplicable
- ValidationsRedeemableSkipped
- ValidationsValidateAllProvidedPromotionsMustBeValidResponseBody
- ValidationsValidateAtLeastOnePromotionMustBeValidResponseBody
- RedeemableResultVoucherCode
- RedeemableResultGiftCard
- RedeemableResultLoyaltyCard
- RedeemableResultPromotionTier
- RedeemableResultPromotionStack
- RedemptionsRedeemResponseBody
- RedemptionsRedemption
- RedemptionsRedemptionBase

**REMOVED ALL DUMMY ENDPOINTS AS WE DON'T USE THEM ANYMORE!!!**

2023-11-02 16:54 UTC, jkaliszuk requested changes

2023-11-02 16:54 UTC, jkaliszuk commented on reference/OpenAPI.json
> +              "INAPPLICABLE"
Tu raczej powinno być SKIPPED

2023-11-02 16:54 UTC, jkaliszuk commented on reference/OpenAPI.json
> +                "$ref": "#/components/schemas/e_error"
To raczej outdated jest. W moim PR ja dodaje nowy obiekt `Error` możesz spróbować sobie to dociągnąć i podmienić może.

2023-11-02 16:54 UTC, jkaliszuk commented on reference/OpenAPI.json
>            "object": {
Tutaj ten enum też na pewno może mieć więcej wartości. Ja sobie np. testuje tutaj z użyciem `promotion_tier`

```
{
    "valid": false,
    "redeemables": [
        {
            "status": "INAPPLICABLE",
            "id": "promo_HD5PHqzGtsa2DHPrvYDEicK9",
            "object": "promotion_tier",
            "result": {
                "error": {
                    "code": 400,
                    "key": "missing_customer",
                    "message": "Missing customer",
                    "details": "Customer is required to validate rules",
                    "request_id": "v-0dc5f408efc056854e"
                }
            }
        },
        {
            "status": "SKIPPED",
            "id": "HAPPY-ORDERcLM",
            "object": "voucher",
            "result": {}
        }
    ]
}
```

2023-11-02 16:54 UTC, jkaliszuk commented on reference/OpenAPI.json
> +            "description": "Lists validation results of each redeemable. If a redeemable can be applied, the API returns `\"status\": \"APPLICABLE\"`.",
Tutaj i niżej ten opis też chyba nie do końca jest właściwy.

2023-11-02 16:54 UTC, jkaliszuk commented on reference/OpenAPI.json
> +      "ValidationsValidateResponseBody": {
Jakoś dziwnie mi diffy pokazuje. Ale generalnie jak znajdziesz sobie `ValidationsValidateRequestBody`. To wydaje mi się, że brakuje tam jeszcze jednego property - `tracking_id`

2023-11-02 17:10 UTC, p-zielinski commented
Thanks @jkaliszuk for the review.
Fixed all.

2023-11-03 09:38 UTC, jkaliszuk approved these changes

2023-11-03 10:10 UTC, merged