Schema naming fix
voucherifyio/voucherify-openapi pull request #612
Opened 2023-12-21 16:28 UTC by p-zielinski

Fixed naming of following schemas:
```
[
  'CustomerRequest',
  'CustomerResponse',
  'ExportCustomersRequest',
  'ExportOrderRequest',
  'ExportPointsExpirationsRequest',
  'ExportPublicationsRequest',
  'ExportRedemptionsRequest',
  'ExportResponseBase',
  'ExportVouchersRequest',
  'ExportVouchersTransactionsExpirationRequest',
  'OrderRequest',
  'OrderRequestBase',
  'OrderResponse',
  'OrderResponseNoCustomerData',
  'SimpleCustomerResponse',
  'ValidationRuleRequest',
  'ValidationRuleResponse',
  'CustomerIdResponse',
  'ExportCustomerRequest',
  'ExportPointsExpirationRequest',
  'ExportPublicationRequest',
  'ExportRedemptionRequest',
  'ExportVoucherRequest',
  'ExportVoucherTransactionsExpirationRequest',
  'OrderItemRequest',
  'OrderResponseBase',
  'ReferrerRequest',
  'ReferrerResponse',
  'CodeConfigResponse',
  'OrderItemResponse'
]
```

2023-12-21 16:50 UTC, jkaliszuk requested changes
Bardzo ładnie, tylko te nazwy schematów do poprawy. Ja też w sumie musze to u siebie poprawić też.

2023-12-21 16:50 UTC, jkaliszuk commented on scripts/md-tables.ts
> +  ["ValidationRule", "VALIDATION-RULES-API-Validation-Rule-Object.md"],
OrderResponse -> OrderCalclated
CustomerResponse -> CustomerWithSummaryLoyaltyReferrals (chyba)

2023-12-21 17:15 UTC, p-zielinski commented on scripts/md-tables.ts
> +  ["ValidationRule", "VALIDATION-RULES-API-Validation-Rule-Object.md"],
było blisko..

2023-12-22 13:27 UTC, p-zielinski commented
Changes were merged to branch `pz/rc-to-rc`, [PR](https://github.com/voucherifyio/voucherify-openapi/pull/613)

2023-12-22 13:27 UTC, closed without merging