Pz/loyalties 3 - part 7
voucherifyio/voucherify-openapi pull request #783
Opened 2024-08-07 07:10 UTC by p-zielinski

- New schemas: `LoyaltiesGetCampaignResponseBody`, `LoyaltiesListCampaignsResponseBody`

2024-08-14 07:01 UTC, p-woznikowski requested changes

2024-08-28 09:21 UTC, p-zielinski commented on reference/OpenAPI.json
> -      "ParameterCode": {
tak, problem w sdk, generalnie kolejność schematów też ma znaczenie.. co mnie troszkę martwi lub denerwuje, ale radzę sobie jeszcze z tym

2024-08-28 09:24 UTC, p-zielinski commented on reference/OpenAPI.json
> +        "description": "Response body schema for **Get** `/loyalties`.",
ciekawa korekta

2024-08-28 09:26 UTC, merged

2024-08-28 09:30 UTC, p-woznikowski commented on reference/OpenAPI.json
> +        "description": "Response body schema for **Get** `/loyalties`.",
Wszędzie jest capsem, to tylko ujednolicam ;)