Refactoring and fixes
voucherifyio/voucherify-openapi pull request #811
Opened 2024-10-09 12:22 UTC by p-zielinski

2024-10-10 17:33 UTC, p-woznikowski requested changes

2024-10-10 17:33 UTC, p-woznikowski commented on reference/OpenAPI.json
> +      "MetadataSchemaDefinition": {
Dla GET List/Get metadata schema(s) tamten poprzedni schemat (`21_obj_metadata_schema_object`) jest prawidłowy. W management jest snake, a dla v1/metadata-schemas i v1/metadata-schemas/{resource} ma być camel.

Trzeba by te camele przekleić stamtąd tutaj.

2024-10-16 08:43 UTC, p-zielinski commented on reference/OpenAPI.json
> +      "MetadataSchemaDefinition": {
So sad

2024-10-16 09:13 UTC, p-woznikowski submitted a review, later dismissed
Zmiany

2024-10-16 09:23 UTC, merged